config files no longer used, now stored in sqlite db, fixed docs spec…
linuxserver/docker-diskover pull request #63
Opened 2024-06-22 12:24 UTC by alex-phillips

…ifying ES authentication, default to off

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [ ] I have read the [contributing](https://github.com/linuxserver/docker-diskover/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

## Benefits of this PR and context:

## How Has This Been Tested?

## Source / References:

2024-06-22 12:43 UTC, thespad commented
This would be a good opportunity to rebase to 3.20 as well

2024-08-24 23:49 UTC, blisst commented
Humble request that the admins merge this!  This took a long time to set up given that the current Docker Compose file in the README does not work as is.

2024-08-27 13:49 UTC, thespad requested changes
Needs rebasing to 3.20 (unless there's some dep, etc. stopping that) - and as part of that the default nginx conf needs updating to remove the `http2` from the listeners as that's now deprecated. 

You haven't updated the arm Dockerfile, is that intentional?

I'd also recommend rerunning the Jenkins builder locally as there's been a big monthly merged since this PR was opened, though it shouldn't break anything if you don't.

2024-09-06 21:38 UTC, thespad approved these changes

2024-09-06 23:45 UTC, merged